### ISSUE TITLE
能否在release里包含您所使用的libmcfgthread-1.dll?

### ISSUE THREAD

**Issue by CCCAUCHY** [eko5624/mpv-win64#12]

**Comment by eko5624** [comment]
我编译的mpv无论是静态编译版还是动态编译版都无需依赖libmcfgthread-1.dll, 所以没有在release里包含。如果需要的话可以直接下载工具链:https://github.com/eko5624/toolchain/releases/download/toolchain/target-gcc-mcf-latest-ucrt-x86_64.7z
libmcfgthread-1.dll所在路径是`target/x86_64-w64-mingw32/bin`

**Comment by CCCAUCHY** [comment]
> 我编译的mpv无论是静态编译版还是动态编译版都无需依赖libmcfgthread-1.dll, 所以没有在release里包含。如果需要的话可以直接下载工具链:https://github.com/eko5624/toolchain/releases/download/toolchain/target-gcc-mcf-latest-ucrt-x86_64.7z libmcfgthread-1.dll所在路径是`target/x86_64-w64-mingw32/bin`

无需依赖吗? 报错提示缺少这个dll, 是有什么问题吗?

**Comment by eko5624** [comment]
从2月5号开始编译的有问题，我排查一下是哪里的问题。

**Comment by eko5624** [comment]
今天编译的应该可以了。(https://github.com/eko5624/mpv-win64/releases/download/2024-02-16/static-mpv.7z)
因为最近编译的mcfgthread改为meson编译了，安装路径错了，所以libmcfgthread.dll.a没删掉导致仍然依赖libmcfgthread-1.dll
