### ISSUE TITLE
Windows7 support

### ISSUE THREAD

**Issue by greenozon** [eko5624/mpv-win64#13]
Hi! does your fork support run on Win7 x64 SP1 ESU?
right now I've tried  mpv-x86_64-20240901-git-7c672e3.7z
and it show the error

```
---------------------------
mpv.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000005). Click OK to close the application. 
---------------------------
OK   
---------------------------

```

**Comment by eko5624** [comment]
mpv drop win7 support officially, so there's nothing we can do.

**Comment by greenozon** [comment]
Could you hint the latest build for W7?
I tried to search but ... looks like it got expired/etc
anyway, thanks, feel free to close the ticket

**Comment by eko5624** [comment]
You can try my build before 2024-05-20.

**Comment by greenozon** [comment]
Thanks! will give it a try shortly
btw, you have very vivid memory if you know it by heart! :)

**Comment by greenozon** [comment]
I really try hard like 10 or so builds before 2024-05-20 but ... same  error
thats is very unfrotunate

one build though thows this instead:
```
---------------------------
mpv.exe - Entry Point Not Found
---------------------------
The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------
```

**Comment by eko5624** [comment]
I did some tests, this is the last build working on win7.
https://github.com/eko5624/mpv-win64/releases/tag/2024-04-29

**Comment by greenozon** [comment]
Great news, 
it does work on WIndows7!
thank you very much for help and communication!

**Comment by eko5624** [comment]
@greenozon

**Comment by greenozon** [comment]
Amazing stuff! kudos!

![image](https://github.com/user-attachments/assets/60b9d09e-a659-4c9b-a51b-ab5836e755c1)


Could I ask you to add some description that this build is Win7 compatible (in download or Release sectino) so that anyone in the future will easily find this build and have a luxury to play H264/265/266/VVC/AV1/etc  medias!

**Comment by greenozon** [comment]
Or maybe make some special note in the repo README file that will point to that W7 compatible build?
Thanks once again for such a great stuff!

**Comment by greenozon** [comment]
example of playing VVC codec media:

![image](https://github.com/user-attachments/assets/bdedef21-b44c-417e-8883-767eb424f098)

**Comment by eko5624** [comment]
Can you upload a sample video with H.266/VCC encode, then I will try to add H.266/VCC dec.

**Comment by greenozon** [comment]
I"m using samples from here:  https://www.elecard.com/videos
