### ISSUE TITLE
avif screenshot support

### ISSUE THREAD

**Issue by CCCAUCHY** [eko5624/mpv-win64#9]
see https://github.com/mpv-player/mpv/issues/12881

also have the same issue with config `screenshot-avif-encoder=libdav1d`

**Comment by eko5624** [comment]
Does this build work for you?
https://github.com/eko5624/mpv-win64/releases/download/2023-11-14/static-mpv-20231114.7z

**Comment by CCCAUCHY** [comment]
> Does this build work for you? https://github.com/eko5624/mpv-win64/releases/download/2023-11-14/static-mpv-20231114.7z

yes
